sudo: false
dist: trusty

language: node_js
node_js:
  - 'node'

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.cache

before_install:
  - npm i -g yarn codecov

install:
  - yarn install --frozen-lockfile
  - yarn cypress install

before_script:
  - git fetch --unshallow

script:
  - yarn build
  - yarn build-zip
  - yarn test:e2e:ci
  - test -f dist/manifest.json
  - test -f dist/background.js
  - test -f dist/vendor.js
  - test -f dist/vendor.css
  - test -f dist/popup/popup.js
  - test -f dist/popup/popup.css
  - test -f dist/options/options.js
  - test -f dist/options/options.css
  - test -f "dist-zip/Solary-v$(node -pe "require('./package.json').version").zip"

before_deploy:
  - export RELEASE_EXTENSION_FILE=$(ls dist-zip/*.zip)
  - echo "Deploying ${RELEASE_EXTENSION_FILE} to GitHub releases"

deploy:
  provider: releases
  api_key:
    secure: xFwQkUCfQpwyYFGICyD32hn2TgpWYSWBKElnBj98f2OnT+92GR+20ZcLWi32wtwuZx4hDrmloY0DVht0OhjseVWmAR9uVnhbCc4j6dbvXVmHeCiothxFBb+IJC4u1xQRmTOgy1lvJZjGa7JeZGvPTxWPxZBQhdgNcfu9mLr5ZtxLfWP88A4B3Y9oSXUx2Wxx5Sl6fZDNH9cfGvMOPPIsSLsnxZ5FTsc8iehnUhp09eYhx5DIT1tUvM8Hey5etxwV0zhkj05nUjxGydk4iELd1pvNVJzArE7R5Goc5Yx8dKhb9HMVfH1CRasfvjWXaGvsLMx+MXkcCarx0GVpHze9wnDczSI6X/wrQlH6hVsvsCXE7jailwF1c7HaEUwzIT6etjAtd8dYrVj7givqGGozfAdk4rVkFbtzX/xtChziPiZIlPH1Tq/C+Bb4YLYe7gkgcXBoddnuu4u88Z1f5zaGKWO8HaiNYF4sETZSp5ARoDIm4Keqw03ZvsXuVggCtGpm7vYT3cFY64MM1z88L1r4f33ZJ9FmM65gecXYoC0QZX5MSdXBKa+6O6LPRfwQN5KAvU0PO85kyzn7w2wg97vkWHlOfyNjLfI1BiOBSwAq5o28hKeb3oaQ/qYRWIOc5Bu5WHIApxhy38eC4Byq61aS7G+jFEyfH8dgXaAQt+U1vb0=
  file: '${RELEASE_EXTENSION_FILE}'
  skip_cleanup: true
  on:
    repo: Kocal-Web-Extensions/Solary
    tags: true
