sudo: false
dist: trusty

language: node_js
node_js:
  - "node"

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.cache

before_install:
  - npm i -g yarn codecov

install:
  - yarn install --frozen-lockfile
  - yarn cypress install

before_script:
  - git fetch --unshallow

script:
  - yarn build
  - yarn build-zip
  - yarn test:e2e:ci
  - test -f dist/manifest.json
  - test -f dist/background.js
  - test -f dist/vendor.js
  - test -f dist/vendor.css
  - test -f dist/popup/popup.js
  - test -f dist/popup/popup.css
  - test -f dist/options/options.js
  - test -f dist/options/options.css
  - test -f "dist-zip/Solary-v$(node -pe "require('./package.json').version").zip"

before_deploy:
  - export RELEASE_EXTENSION_FILE=$(ls dist-zip/*.zip)
  - echo "Deploying ${RELEASE_EXTENSION_FILE} to GitHub releases"

deploy:
  provider: releases
  api_key:
    secure: NNZIAQpo/DM59eD3tZv7mrUy6Symw/VrhedarMeHylQ+e5/h3qIHT9oVc5Ijv3onarp7ZWGLyAmw+VRT4p/ew2KcFl1NPaWlDDHdEveXYFwhPIbIm3yeay7x8Q9/Yz9rL4RIXN7x4PrCB02slLmQyn3tCFArrOuORWz3Qu+b9mzaJPFgZ7Kn4W+NOg+xvNvZm5RU7oywKva9pjud2KnvrtfKz6JNwPGKZVmB4i0XZFsBof80yxfJw4wvZcKEAVGfxVyrBad/yfTzoZWe4MX2yHkYjTvWqKUW8AsOZjqd6pygQLiR33R+u7Lw4joqjUrIV4glkyYNGwsZclRx1ywmqpY/OH6DOkDWHzzRioXfcaO7rxyHongkrXJOx+WUc+rBkCI6wdC+4tdzvI81N8nH71MH/+63vTyrItxgLrhjMH3TR2K6YlqLQC3yrosdUCLbXXZaGwXuhkdekLDUsLFiJEWQF1es9uxy07Ee9WQ5El3LqPX9aKLln9VWwmffEFZxsfk1jUo/F/4NskQnJ1hOanUKaT7+wgaLEGvLKaVpAtIViQA/m4aaWto9K4MUztogyOpRhscjxI+Z3AyknwKv83nUVhtT3Q1D7dQH6mv5R0E7ttWCBb89ZiIY0pMF2CshQUSN52/omOjpIPTzkxNhy/7XXJ9sB0tr8rfUpdK5fG8=
  file: "${RELEASE_EXTENSION_FILE}"
  skip_cleanup: true
  on:
    repo: Kocal-Web-Extensions/Solary
    tags: true
