sudo: false
dist: trusty

language: node_js
node_js:
  - "node"

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add codecov

before_script:
  - git fetch --unshallow
  - yarn

script:
  - yarn build
  - yarn build-zip
  - yarn test && codecov
  - test -f dist/manifest.json
  - test -f dist/background.js
  - test -f dist/vendor.js
  - test -f dist/vendor.css
  - test -f dist/popup/popup.js
  - test -f dist/popup/popup.css
  - test -f dist/options/options.js
  - test -f dist/options/options.css
  - test -f "dist-zip/Solary-v$(node -pe "require('./package.json').version").zip"

before_deploy:
  - export RELEASE_EXTENSION_FILE=$(ls dist-zip/*.zip)
  - echo "Deploying ${RELEASE_EXTENSION_FILE} to GitHub releases"

deploy:
  provider: releases
  api_key:
    secure: J9X/2T8NrBYSuCxRAV09ZSnM+vARc6evzYgFwrElV8AJ6+iH3X5QWUvRAILdBXc1R48tIUEPjtPfIl/EB0rwUHEiqvhpQ90kaXSzbQwPi2fgY9zVaVC0OwRin7Y64LnLLAcGRnN8DztmSbFHM6TFdlaCmhBT+HKBrnNrGnIAEOIDN9pd3vYolYCViWxZEprvXKdWUKnHOZ7V5P66d6TzMjiVyHDhOeqYRplurRmi1yUMufFw4N8/w2Fu8BwDEdKqY8p9GwnZaElj59RjTZXx6YcM9RRGjw9zuvC/qbP5h6JF28gvWD60bk8+x73d8yquKSk09DsgtthGdCVBEkHj1yHCVeAT8CFrBJ6YUkUgCV//EyfnR0blj3vX8dCg0KdA59ZwsXDoZ/h/5lEXBtpUHVcXaSDIslGtyN063WoS5guv1/0u7FpwtuoM+zDg7xynRs7eMnd1flFyxYIJZw0t4aUczfBH9C4EMMHGBUkX8OR7GwociEo8vULCP8TAfJYqIzMYTH2gZfmLvj7IxFbZdBTBGpfbTkrAkhSzNEV3I6eA0fTsfmppegybXn48WSfzYWloGNaV1uWz25rGPEZFgXxuvvcNpwK4tgyq2O6dxXHTeLCgee7yPx8ppCf1nNgUmqp2Eh0Gh1IJACulxf0gxXHEnYgB6nvoUME07nkeSWs=
  file: "${RELEASE_EXTENSION_FILE}"
  skip_cleanup: true
  on:
    repo: Kocal/Solary
    tags: true
