sudo: false
dist: trusty

language: node_js
node_js:
  - "node"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - yarn
  - yarn bootstrap

script:
  - yarn lint
  - bash ci/build-extension.sh
  - bash ci/test-extension.sh
  - bash ci/run-server.sh
  - bash ci/test-server.sh
  - bash ci/stop-server.sh
